title:              윤진의 IT 블로그
email:              gzblues61@daum.net
description:        Network, Kubernetes, etc...
author:             이윤진(Lee Yunjin)<gzblues61@daum.net>
favicon:            /img/favicon.ico
default_thumbnail:  /img/default-fetured.jpg
baseurl:            ""
url:                "https://gg582.github.io"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM


# Social Profiles
twitter_username: 
github_username: gg582
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

collections:
  embedded:
    output: true
    permalink: /embedded/:path/
  codingtest:
    output: true
    permalink: /codingtest/:path/
  cloud:
    output: true
    permalink: /cloud/:path/
  network:
    output: true
    permalink: /network/:path

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
