title:              Lee Yunjin's Blog
email:              gg582@naver.com
description:        Yunjin's Portfolio 
author:             Lee Yunjin 
baseurl:            ""
url:                "https://gg582.github.io"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM


# Social Profiles
twitter_username: 
github_username: gg582
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

collections:
  embedded:
    output: true
    permalink: /embedded/:path/
  codingtest:
    output: true
    permalink: /codingtest/:path/
  network:
    output: true
    permalink: /network/:path

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
